from __future__ import annotations

from typing import Any, Protocol


class VectorStorePort(Protocol):
    def is_ready(self) -> bool: ...

    def count(self) -> int: ...

    def query(self, query_text: str, top_k: int) -> list[dict[str, Any]]: ...

    def upsert(self, chunks: list[dict[str, Any]]) -> None: ...

    def delete_by_source(self, source_path: str) -> bool: ...
